# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-10 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='club_fk',
        ),
        migrations.AddField(
            model_name='employee',
            name='club_m2m',
            field=models.ManyToManyField(blank=True, null=True, to='nomenclature.Club', verbose_name='Клуб'),
        ),
    ]
