# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-09 02:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import tartRequests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nomenclature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TortaRequestPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(blank=True, null=True, upload_to='tartImages/ЗАЯВКИ', verbose_name='Изображение')),
                ('last_update_date', models.DateTimeField(blank=True, db_column='LAST_UPDATE_DATE', default=datetime.datetime(2017, 5, 9, 2, 30, 47, 697023, tzinfo=utc), null=True, verbose_name='Дата промяна')),
            ],
            options={
                'verbose_name_plural': 'Собствени изображения за торта',
                'verbose_name': 'Собствено изображение за торта',
                'managed': False,
                'db_table': 'tart_req_pictures',
            },
        ),
        migrations.CreateModel(
            name='TortaPictureRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(blank=True, max_length=200, null=True, upload_to=tartRequests.models.TortaPictureRegister.upload_storage, verbose_name='Изображение')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Код')),
                ('tart_type', models.CharField(blank=True, choices=[('3D', '3D'), ('Захарна плака', 'Захарна плака'), ('Стандартна', 'Стандартна')], max_length=50, verbose_name='Тип')),
                ('category', models.CharField(blank=True, max_length=150, verbose_name='Категория')),
                ('description', models.TextField(blank=True, max_length=400, verbose_name='Описание')),
                ('last_update_date', models.DateTimeField(blank=True, db_column='LAST_UPDATE_DATE', default=datetime.datetime(2017, 5, 9, 2, 30, 47, 697524, tzinfo=utc), null=True, verbose_name='Дата промяна')),
            ],
            options={
                'verbose_name_plural': 'Регистър на торти',
                'verbose_name': 'Регистър на торти',
                'managed': True,
                'db_table': 'tart_picture_register',
            },
        ),
        migrations.CreateModel(
            name='TortaPieceCoding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tart_type', models.CharField(choices=[('3D', '3D'), ('Захарна плака', 'Захарна плака'), ('Стандартна', 'Стандартна')], max_length=50, verbose_name='Тип')),
                ('torta_cnt', models.IntegerField(db_column='TORTA_CNT', verbose_name='Брой парчета')),
                ('levels', models.IntegerField(db_column='LEVLES', verbose_name='Етажи')),
                ('tart_size', models.CharField(db_column='TART_SIZE', max_length=50, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Брой Парчета',
                'verbose_name': 'Брой Парчета',
                'managed': True,
                'db_table': 'tart_piece_coding',
            },
        ),
        migrations.CreateModel(
            name='TortaRequest',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='Ном.')),
                ('code', models.CharField(db_column='CODE', max_length=50, verbose_name='Кат.Номер')),
                ('tart_type', models.CharField(db_column='TART_TYPE', max_length=50, verbose_name='Вид')),
                ('tart_size', models.CharField(db_column='TART_SIZE', max_length=50, null=True, verbose_name='Големина')),
                ('torta_cnt', models.IntegerField(db_column='TORTA_CNT', null=True, verbose_name='Брой парчета')),
                ('palnej', models.CharField(blank=True, db_column='PALNEJ', default='-----', max_length=100, verbose_name='Пълнеж')),
                ('nadpis', models.CharField(blank=True, db_column='NADPIS', max_length=150, verbose_name='Надпис')),
                ('tart_name', models.CharField(blank=True, db_column='TART_NAME', max_length=100, verbose_name='Вкус')),
                ('price', models.FloatField(db_column='PRICE', null=True, verbose_name='Ед.Цена')),
                ('notes', models.TextField(blank=True, db_column='NOTES', max_length=3000, verbose_name='Забележка')),
                ('dostavka_date', models.DateTimeField(db_column='DOSTAVKA_DATE', null=True, verbose_name='Дата доставка')),
                ('delivery_address', models.TextField(blank=True, db_column='DELIVERY_ADDRESS', max_length=1000, verbose_name='Адрес на доставка')),
                ('client_phone', models.CharField(blank=True, db_column='CLIENT_PHONE', max_length=50, verbose_name='Телефон')),
                ('changes', models.TextField(blank=True, db_column='CHANGES', max_length=3000, verbose_name='История на промените')),
                ('reg_date', models.DateTimeField(db_column='REG_DATE', default=datetime.datetime(2017, 5, 9, 2, 30, 47, 695522, tzinfo=utc), verbose_name='Дата заявка')),
                ('last_update_date', models.DateTimeField(blank=True, db_column='LAST_UPDATE_DATE', null=True, verbose_name='Дата промяна')),
                ('status', models.CharField(choices=[('NEW', 'Нова'), ('OPEN', 'Заявена'), ('DELIVERED', 'Доставена'), ('PAYED', 'Платена')], db_column='STATUS', default='NEW', max_length=50, verbose_name='Статус')),
                ('club_fk', models.ForeignKey(db_column='CLUB_ID', default=1, on_delete=django.db.models.deletion.CASCADE, to='nomenclature.Club', to_field='club_id', verbose_name='Клуб')),
                ('user_fk', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заявител')),
            ],
            options={
                'verbose_name_plural': 'Заявки за торта',
                'verbose_name': 'Заявка за торта',
                'managed': True,
                'db_table': 'tart_req',
            },
        ),
        migrations.CreateModel(
            name='TortaTasteRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palnej', models.CharField(blank=True, max_length=50, verbose_name='Пълнеж')),
                ('level', models.IntegerField(verbose_name='Макс. Етаж')),
                ('price', models.FloatField(null=True, verbose_name='Ед.Цена')),
                ('last_update_date', models.DateTimeField(blank=True, db_column='LAST_UPDATE_DATE', default=datetime.datetime(2017, 5, 9, 2, 30, 47, 696523, tzinfo=utc), null=True, verbose_name='Дата промяна')),
            ],
            options={
                'verbose_name_plural': 'Вкусове за торта',
                'verbose_name': 'Вкус за торта',
                'managed': True,
                'db_table': 'tart_taste_register',
            },
        ),
        migrations.AddField(
            model_name='tortapictureregister',
            name='torta_tase_fk',
            field=models.ManyToManyField(to='tartRequests.TortaTasteRegister', verbose_name='Вкусове'),
        ),
    ]
