# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-09 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tartrequests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tortapictureregister',
            name='last_update_date',
            field=models.DateTimeField(blank=True, db_column='LAST_UPDATE_DATE', default=django.utils.timezone.now, null=True, verbose_name='Дата промяна'),
        ),
        migrations.AlterField(
            model_name='tortarequest',
            name='reg_date',
            field=models.DateTimeField(db_column='REG_DATE', default=django.utils.timezone.now, verbose_name='Дата заявка'),
        ),
        migrations.AlterField(
            model_name='tortatasteregister',
            name='last_update_date',
            field=models.DateTimeField(blank=True, db_column='LAST_UPDATE_DATE', default=django.utils.timezone.now, null=True, verbose_name='Дата промяна'),
        ),
    ]
