# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-09 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tartrequests', '0002_auto_20170509_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='TortaPictureCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=150, verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'managed': True,
                'verbose_name': 'Категория',
                'db_table': 'tart_category',
            },
        ),
        migrations.AlterField(
            model_name='tortapictureregister',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tartrequests.TortaPictureCategory', verbose_name='Категория'),
        ),
    ]
