# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-09 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tartrequests', '0004_auto_20170509_0850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TortaRequestPicture',
        ),
    ]
