# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-09 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tartrequests', '0005_delete_tortarequestpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='TortaRequestPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(blank=True, null=True, upload_to='tartImages/ЗАЯВКИ', verbose_name='Изображение')),
                ('last_update_date', models.DateTimeField(blank=True, db_column='LAST_UPDATE_DATE', default=django.utils.timezone.now, null=True, verbose_name='Дата промяна')),
                ('torta_rq_fk', models.ForeignKey(db_column='tart_id', on_delete=django.db.models.deletion.CASCADE, to='tartrequests.TortaRequest')),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'Собствени изображения за торта',
                'verbose_name': 'Собствено изображение за торта',
                'db_table': 'tart_req_pictures',
            },
        ),
    ]
