# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-20 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('tartrequests', '0006_tortarequestpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='TortaDeliveryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField(blank=True, db_column='DELIVERY_ADDRESS', max_length=1000, verbose_name='Адрес на доставка')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Група')),
            ],
        ),
    ]
