# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-20 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tartrequests', '0007_tortadeliveryaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tortadeliveryaddress',
            options={'managed': True, 'verbose_name': 'Адрес за доставка', 'verbose_name_plural': 'Адреси за доставка'},
        ),
        migrations.AlterField(
            model_name='tortadeliveryaddress',
            name='delivery_address',
            field=models.CharField(db_column='DELIVERY_ADDRESS', max_length=1000, verbose_name='Адрес на доставка'),
        ),
    ]
