# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-21 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tartrequests', '0008_auto_20170520_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tortarequest',
            name='changes',
        ),
        migrations.AlterField(
            model_name='tortarequest',
            name='club_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclature.Club', verbose_name='Клуб'),
        ),
        migrations.AlterField(
            model_name='tortarequest',
            name='delivery_address',
            field=models.TextField(blank=True, db_column='DELIVERY_ADDRESS', max_length=1000, null=True, verbose_name='Адрес на доставка'),
        ),
    ]
