# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-21 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tartrequests', '0009_auto_20170521_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tortapictureregister',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Код'),
        ),
    ]
