# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-21 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tartrequests', '0012_remove_tortapictureregister_torta_tase_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tortarequest',
            name='code',
            field=models.ForeignKey(db_column='CODE', on_delete=django.db.models.deletion.CASCADE, to='tartrequests.TortaPictureRegister', to_field='code', verbose_name='Кат.Номер'),
        ),
        migrations.AlterField(
            model_name='tortarequest',
            name='palnej',
            field=models.ForeignKey(db_column='PALNEJ', on_delete=django.db.models.deletion.CASCADE, to='tartrequests.TortaTasteRegister', verbose_name='Пълнеж'),
        ),
    ]
