# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-21 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tartrequests', '0013_auto_20170521_0805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tortarequest',
            options={'managed': True, 'permissions': (('change_tortarequest', 'Променя Заявка за торта'), ('add_tortarequest', 'Добавя Заявка за торта'), ('delete_tortarequest', 'Изтрива Заявка за торта'), ('view_tortarequest_calendar', 'Календар за Заявка за торта')), 'verbose_name': 'Заявка за торта', 'verbose_name_plural': 'Заявки за торта'},
        ),
        migrations.AlterField(
            model_name='tortarequest',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tartrequests.TortaPictureRegister', verbose_name='Кат.Номер'),
        ),
        migrations.AlterField(
            model_name='tortarequest',
            name='id',
            field=models.AutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='Рег. Номер  '),
        ),
        migrations.AlterField(
            model_name='tortarequestpicture',
            name='filename',
            field=models.FileField(blank=True, null=True, upload_to='tartImages/ВЪНШНИ ЗАЯВКИ', verbose_name='Изображение'),
        ),
    ]
