# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-21 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tartrequests', '0014_auto_20170521_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tortarequest',
            options={'default_permissions': (), 'managed': True, 'permissions': (('change_tortarequest', 'Променя Заявка за торта'), ('add_tortarequest', 'Добавя Заявка за торта'), ('delete_tortarequest', 'Изтрива Заявка за торта'), ('view_tortarequest_calendar', 'Календар за Заявка за торта')), 'verbose_name': 'Заявка за торта', 'verbose_name_plural': 'Заявки за торта'},
        ),
    ]
