# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-21 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tartrequests', '0015_auto_20170521_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tortatasteregister',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ед.Цена'),
            preserve_default=False,
        ),
    ]
