# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-22 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tartrequests', '0016_auto_20170521_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tortarequest',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tortarequest',
            name='tart_name',
        ),
        migrations.RemoveField(
            model_name='tortarequest',
            name='tart_type',
        ),
        migrations.RemoveField(
            model_name='tortarequest',
            name='torta_cnt',
        ),
        migrations.AlterField(
            model_name='tortarequest',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tartrequests.TortaPictureRegister', verbose_name='Кат.No:Тип:Категория'),
        ),
        migrations.AlterField(
            model_name='tortarequest',
            name='tart_size',
            field=models.ForeignKey(db_column='TART_SIZE', null=True, on_delete=django.db.models.deletion.CASCADE, to='tartrequests.TortaPieceCoding', verbose_name='Големина'),
        ),
    ]
