# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-10 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0003_auto_20170610_1509'),
        ('tartrequests', '0018_auto_20170603_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='tortapiececoding',
            name='club_m2m',
            field=models.ManyToManyField(to='nomenclature.Club', verbose_name='За клуб'),
        ),
    ]
