# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-11 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0003_auto_20170610_1509'),
        ('tartrequests', '0019_tortapiececoding_club_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='TortaPricePerClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tart_type', models.CharField(blank=True, choices=[('3D', '3D'), ('Захарна плака', 'Захарна плака'), ('Стандартна', 'Стандартна')], max_length=50, verbose_name='Тип')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ед.Цена')),
                ('last_update_date', models.DateTimeField(blank=True, db_column='LAST_UPDATE_DATE', default=django.utils.timezone.now, null=True, verbose_name='Дата промяна')),
                ('club_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclature.Club', verbose_name='Клуб')),
            ],
            options={
                'verbose_name': 'Цена за торта',
                'db_table': 'tart_prices',
                'verbose_name_plural': 'Цени за торти',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='tortatasteregister',
            name='price',
        ),
    ]
