# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-08 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ostrovaweb.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomenclature', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashdesk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('rec_date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('beg_bank_100', models.IntegerField(blank=True, null=True, verbose_name='Банкноти по 100')),
                ('beg_bank_50', models.IntegerField(blank=True, null=True, verbose_name='Банкноти по 50')),
                ('beg_bank_20', models.IntegerField(blank=True, null=True, verbose_name='Банкноти по 20')),
                ('beg_bank_10', models.IntegerField(blank=True, null=True, verbose_name='Банкноти по 10')),
                ('beg_bank_5', models.IntegerField(blank=True, null=True, verbose_name='Банкноти по 5')),
                ('beg_bank_2', models.IntegerField(blank=True, null=True, verbose_name='Банкноти по 2')),
                ('beg_coin_100', models.IntegerField(blank=True, null=True, verbose_name='Стотинки по 100')),
                ('beg_coin_50', models.IntegerField(blank=True, null=True, verbose_name='Стотинки по 50')),
                ('beg_coin_20', models.IntegerField(blank=True, null=True, verbose_name='Стотинки по 20')),
                ('beg_coin_10', models.IntegerField(blank=True, null=True, verbose_name='Стотинки по 10')),
                ('beg_coin_5', models.IntegerField(blank=True, null=True, verbose_name='Стотинки по 5')),
                ('beg_close_date', models.DateField(blank=True, null=True, verbose_name='Дата на предаване')),
                ('beg_open_date', models.DateField(blank=True, null=True, verbose_name='Дата на приемане')),
                ('end_bank_100', models.IntegerField(blank=True, null=True, verbose_name='Банкноти по 100')),
                ('end_bank_50', models.IntegerField(blank=True, null=True, verbose_name='Банкноти по 50')),
                ('end_bank_20', models.IntegerField(blank=True, null=True, verbose_name='Банкноти по 20')),
                ('end_bank_10', models.IntegerField(blank=True, null=True, verbose_name='Банкноти по 10')),
                ('end_bank_5', models.IntegerField(blank=True, null=True, verbose_name='Банкноти по 5')),
                ('end_bank_2', models.IntegerField(blank=True, null=True, verbose_name='Банкноти по 2')),
                ('end_coin_100', models.IntegerField(blank=True, null=True, verbose_name='Стотинки по 100')),
                ('end_coin_50', models.IntegerField(blank=True, null=True, verbose_name='Стотинки по 50')),
                ('end_coin_20', models.IntegerField(blank=True, null=True, verbose_name='Стотинки по 20')),
                ('end_coin_10', models.IntegerField(blank=True, null=True, verbose_name='Стотинки по 10')),
                ('end_coin_5', models.IntegerField(blank=True, null=True, verbose_name=' Стотинки по 5')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата на създавне')),
                ('last_update_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата на промяна')),
                ('status', models.CharField(choices=[('OPENED', 'ОТВОРЕНА'), ('JUSTCLOSED', 'ПОСЛЕДНО ЗАТВОРЕНА'), ('CLOSED', 'ЗАТВОРЕНА')], default='OPENED', max_length=80, verbose_name='Статус')),
            ],
            options={
                'managed': True,
                'verbose_name': 'Каса',
                'verbose_name_plural': 'Каси',
                'db_table': 'cashdesk',
            },
            bases=(ostrovaweb.utils.AdminURLMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Cashdesk_detail_expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('note', models.CharField(blank=True, max_length=400, null=True, verbose_name='Забележка')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сума')),
                ('cashdesk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashdesk.Cashdesk', verbose_name='Каса')),
            ],
            options={
                'managed': True,
                'verbose_name': 'Разходен касов ордер',
                'verbose_name_plural': 'Разходни касови ордери',
                'db_table': 'cashdesk_detail_expense',
            },
        ),
        migrations.CreateModel(
            name='Cashdesk_detail_income',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('note', models.CharField(blank=True, max_length=400, null=True, verbose_name='Забележка')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сума')),
                ('cashdesk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashdesk.Cashdesk', verbose_name='Каса')),
                ('group_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclature.Cashdesk_groups_income', verbose_name='Група приходи')),
                ('order_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='Плащане по поръчка')),
                ('transfer_club_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashdesk_detail_income_transfer_set', to='nomenclature.Club', verbose_name='Към обект')),
                ('transfer_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashdesk.Cashdesk_detail_expense', verbose_name='Трансфер')),
            ],
            options={
                'managed': True,
                'verbose_name': 'Приходен касов ордер',
                'verbose_name_plural': 'Приходни касови ордери',
                'db_table': 'cashdesk_detail_income',
            },
        ),
    ]
