# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-08 22:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('nomenclature', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdesk_detail_expense',
            name='delivery_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.Delivery', verbose_name='Плащане по доставка'),
        ),
        migrations.AddField(
            model_name='cashdesk_detail_expense',
            name='group_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclature.Cashdesk_groups_expense', verbose_name='Група разходи'),
        ),
        migrations.AddField(
            model_name='cashdesk_detail_expense',
            name='transfer_club_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashdesk_detail_expense_transfer_set', to='nomenclature.Club', verbose_name='Към обект'),
        ),
        migrations.AddField(
            model_name='cashdesk_detail_expense',
            name='transfer_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashdesk.Cashdesk_detail_income', verbose_name='Трансфер'),
        ),
        migrations.AddField(
            model_name='cashdesk',
            name='beg_close',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beg_close', to=settings.AUTH_USER_MODEL, verbose_name='Предал'),
        ),
        migrations.AddField(
            model_name='cashdesk',
            name='beg_open',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beg_open', to=settings.AUTH_USER_MODEL, verbose_name='Приел'),
        ),
        migrations.AddField(
            model_name='cashdesk',
            name='club_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nomenclature.Club', verbose_name='Обект'),
        ),
        migrations.CreateModel(
            name='Cashdesk_detail_transfer',
            fields=[
            ],
            options={
                'verbose_name': 'Касов трансфер',
                'verbose_name_plural': 'Касови трансфери',
                'proxy': True,
            },
            bases=('cashdesk.cashdesk_detail_expense',),
        ),
    ]
